name: Deploy Artifacts

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        description: Version to author


jobs:
  upload_artifacts:
    name: Deploy Artifacts ${{ matrix.host }}/${{ matrix.target }}
    runs-on:
      - self-hosted
      - linux
      - repo-release
    environment: release
    strategy:
      matrix:
        host:
          - x86_64
          - aarch64
        target:
          - x86_64
          - aarch64
    steps:

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: toolchain-${{ matrix.host }}-${{ matrix.target }}-linux-gnu.tar.xz
        path: release-artifacts/
    
    - name: Get Salt Project GitHub Actions Bot Environment
      id: spb-environment
      run: |
        TOKEN=$(curl -sS -f -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 30")
        SPB_ENVIRONMENT=$(curl -sS -f -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/tags/instance/spb:environment)
        echo "spb-environment=$SPB_ENVIRONMENT" >> "$GITHUB_OUTPUT"
    
    - name: Install `awscli`
      run: |
        pip3 install awscli

    - name: "Deploy Toolchain: ${{ matrix.host }}/${{ matrix.target }}-linux-gnu.tar.xz"
      run: |
        aws s3 cp release-artifacts/* s3://salt-project-${{ steps.spb-environment.outputs.spb-environment }}-salt-artifacts-release/relenv/${{ inputs.version }}/toolchain/${{ matrix.host }}/${{ matrix.target }}-linux-gnu.tar.xz
  
