name: Deploy Artifacts

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        description: Version to author
    secrets:
      SSHKEY:
        required: true


jobs:
  upload_artifacts:
    name: Deploy Artifacts ${{ matrix.python }}-${{ matrix.arch }}-${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
            - 3.10.9
            - 3.11.1
        include:
          - platform: linux-gnu
            arch: aarch64
          - platform: linux-gnu
            arch: x86_64
          - platform: win
            arch: x86
          - platform: win
            arch: amd64
          - platform: macos
            arch: x86_64
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SSHKEY: ${{ secrets.SSHKEY }}
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.python }}-${{ matrix.arch }}-${{ matrix.platform }}.tar.xz

    - name: Setup Private Key
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${SSHKEY}" | tr -d '\r' | ssh-add -

    - name: Setup Private Key
      run: |
        mkdir -p /home/runner/.ssh
        touch /home/runner/.ssh/known_hosts
        ssh-keyscan d1.h4.cx >> /home/runner/.ssh/known_hosts

    - name: Ensure Build Directory Exists
      run: |
        ssh cicd@d1.h4.cx mkdir -p /var/www/woz.io/relenv/${{ inputs.version }}/build/

    - name: "Deploy Python Build: ${{ matrix.python }}-${{ matrix.host }}-${{ matrix.platform }}.tar.xz"
      run: |
        scp ${{ matrix.python }}-${{ matrix.arch }}-${{ matrix.platform }}.tar.xz "cicd@d1.h4.cx:/var/www/woz.io/relenv/${{ inputs.version }}/build/"
