name: Relenv Python Package

on: workflow_call

jobs:
  build:
    name: Publish Python Wheel
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Download Python Package Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
          skip-existing: true
          verify-metadata: true
